sonarr:
    api_key: ENC[AES256_GCM,data:dqrfjeU=,iv:eytV0NFaPLydYkelsKl0aNBlTImkmNJc0At3iS+c+z0=,tag:9eE8QWLmcDvFZZzMYm57Jg==,type:str]
    password: ENC[AES256_GCM,data:+8Lzvg==,iv:3DO+xw8Wqvx557ZqBBJ8MemlqYQAwH/ASMRX4+8eLZE=,tag:wxv67uBnU2WapTPWiRunHA==,type:str]
prowlarr:
    api_key: ENC[AES256_GCM,data:AQanhDs=,iv:wJnOjMqyPqwJwqqO1IsrCrlEa0OMNQFn0tuxnRU0aC8=,tag:sPCzicMpgowWUPDViXWuxA==,type:str]
    password: ENC[AES256_GCM,data:uFc4MA==,iv:uCE25Pxn1Us1XHCppExjDCjvw3a5SxvzcLUVYBRkyfE=,tag:NHWwlehTrJBHxkAylaE/SQ==,type:str]
sabnzbd:
    api_key: ENC[AES256_GCM,data:+/CHfP8=,iv:8qL3XdOPYNIhvun/nA9sIhx1t2UyCCX5pwMGaK0YYrI=,tag:zqwKQqOnlDqLmlRTu25CiA==,type:str]
jellyfin:
    admin_password: ENC[AES256_GCM,data:C33QgF0=,iv:+LYHq+CGwAmWlLP2g6Sk8ewIjNInDxIiY1Fgg4jJC8I=,tag:aUFqMW8vVgf1X1h1p/PTdQ==,type:str]
    api_key: ENC[AES256_GCM,data:G3xhzQ==,iv:jLmvMzVLBjR7S6NFWu1fjG3EJqdqC0w+ll3otg9O1yo=,tag:VD8Ya4Khb156liDfZA7guA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YzlReG9IZ2xPTldJVTVa
            QmpQcVNHOUxqSG43VU5JS2RYZXdnUGJWZzFvCitCSmREWC84bEZBOEI2M1VwWEMv
            V21aMFNORXcyNFJ4Nm5rdkx1LzVXdTgKLS0tIFh0RnlIOEMwUGZ2YWhDQ2QyZXAv
            ZU1tQjhkQ2FHZ2VObzZiTTRDN2RkYk0Ko4cuA62Vv48XN5pdcJnU5cKGEnShjrQb
            ewmVXWVdHaxDAim8LecdoPVvQ48v8up/fINX+RGSsyKeBWIi8kU8JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1up9jfu39893zyguz3tk8zhqe2gxxhkdrppst47mr9d0lc6cz3ejqaywygw
    lastmodified: "2026-07-12T22:49:29Z"
    mac: ENC[AES256_GCM,data:3iAzXdI2oOedxO4CrLDIVFwzy0Zd8NmehaDXc0bLRH4Ige88ZQ9rqRxgfISFq4DZPJJ1utsfMIJdJAQtuqkSob9vL2IQ7jg6wd/2MypVhQS/uL+nLAahwwFlHQ0CtE5MfMpU3exy0g8J6MyhW9vd3OY+uT5kNITdxf2CiSfRKhU=,iv:jsc4FamyOMBscPysssgm4MCl8737TWF6w0Fn/yBlmP4=,tag:cdWf77wTv+qhBM5a8Iko+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
