sonarr:
    api_key: ENC[AES256_GCM,data:U9jXGvoyK+WbfVnMBW9TosAC4VPjdks4RsVKC4AtfcA=,iv:DP6eMmTyDMPSKPq5vYqQJdbEFDio2RCzLVUPK+uVmaM=,tag:nJVb5zCNLm+nOoPUPCLzpA==,type:str]
    password: ENC[AES256_GCM,data:+1Cm6hgit+wizd0=,iv:l4skkO/Zw3DJfu0aSNYYNrxR1MQH2BqfOuo1h6bQyZs=,tag:AfCH3XfPRropQd3CFfVKyg==,type:str]
prowlarr:
    api_key: ENC[AES256_GCM,data:jLd1rzhmUpQ+6Qs07/D5W0vWXuuF7Lf6i1LJG6I3ug==,iv:j2V8YH9Pi52mOj2pH8OA7LHj25mIc2T54zL9ZlCIzX4=,tag:sEoHaxtv5NhnmrO2c4RZnw==,type:str]
    password: ENC[AES256_GCM,data:jEOl8sHXDY7Z0E8=,iv:FrJU+ijoQWKbjMZENRHASNQiIpexKhQDi6K5OnR0/UM=,tag:5W154xEs8sOoDWXdBSEMIQ==,type:str]
sabnzbd:
    api_key: ENC[AES256_GCM,data:xGV5VZvgiurprOMuxWY8fIXw11oog+5g9goNZTBzlt0=,iv:/FcahPsf+ijl14upWChXMfdMjm0goSc+hvCaLjFyCNE=,tag:UuH/a7eapUYTpQl3FzGJzw==,type:str]
jellyfin:
    admin_password: ENC[AES256_GCM,data:HfJhiXT/02dol6Y=,iv:RmfW7T4jqNMDGtmYQFSX0LXkO/fkrNXtsHWQwecCNog=,tag:xDOTGyGuN6BmGiCjCiqyQA==,type:str]
    api_key: ENC[AES256_GCM,data:u1swWsWlUQ9SwBjDerm3xS/DW61emMm5Mdh6cCzl,iv:RhS2G3YewrYbUCc1tcmmP63FfeyVpaPDzEgk9DYcpgU=,tag:Gx/FxBdLiWLJ9tKyCT51nA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YzlReG9IZ2xPTldJVTVa
            QmpQcVNHOUxqSG43VU5JS2RYZXdnUGJWZzFvCitCSmREWC84bEZBOEI2M1VwWEMv
            V21aMFNORXcyNFJ4Nm5rdkx1LzVXdTgKLS0tIFh0RnlIOEMwUGZ2YWhDQ2QyZXAv
            ZU1tQjhkQ2FHZ2VObzZiTTRDN2RkYk0Ko4cuA62Vv48XN5pdcJnU5cKGEnShjrQb
            ewmVXWVdHaxDAim8LecdoPVvQ48v8up/fINX+RGSsyKeBWIi8kU8JA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1up9jfu39893zyguz3tk8zhqe2gxxhkdrppst47mr9d0lc6cz3ejqaywygw
    lastmodified: "2026-07-13T02:24:44Z"
    mac: ENC[AES256_GCM,data:TilbAiR2qbaxV7EXJAcMdpwtHoWbDTaDIgTQ8icilr0vdmK72fq3xrUFyM1MEZInrnRPVLfdFeOBs8K3nOAvtNgjWiOsMYrieByyiWPsuPQMCdM41gVurmn5ljgCbAAwQHkAuuDrZhZvzf+By3YBHVZo8PZzof2BZFWtqcVov4w=,iv:vw41BqO34+WPzBX9ZEnfhDyq8F4fMBAGh5c0ukGDonY=,tag:VsF47mc0PA8GbTOcaHz4wA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
