preload = ~/.dotfiles/backgrounds/space.png
splash = false
# exec-once = kitty +kitten panel --edge=background -o font_size=12 cmatrix
# wallpaper = , ~/.dotfiles/backgrounds/space.png
wallpaper {
  monitor = 
  path = ~/.dotfiles/backgrounds/space.png
}
